services:
  - type: web
    name: pong-online-game
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: pong-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1